/**
 * Every Italian region's boundary (ISTAT 2025, generalised and simplified to ~500 m), keyed by the
 * registry's slug. `boundaries.json` is generated by `uv run python -m api.grid.web_boundaries`
 * (api/src/api/grid/web_boundaries.py); don't edit it by hand.
 */

export interface RegionBoundaryProperties {
  /** The registry slug (`toscana`, `emilia-romagna`): served or not. */
  slug: string
  /** ISTAT `COD_REG`. */
  code: number
  /** ISTAT's Italian name. */
  name: string
  /** A point well inside the region's largest part, for its label: `[lon, lat]`. */
  label: [number, number]
}

export type RegionBoundaries = GeoJSON.FeatureCollection<
  GeoJSON.Polygon | GeoJSON.MultiPolygon,
  RegionBoundaryProperties
>

/**
 * Its own chunk (~50 KB gzipped), fetched only by what draws it. Read as text: TypeScript would
 * otherwise infer a literal type for every coordinate, and JSON.parse is faster than a JS literal.
 */
export const loadRegionBoundaries = (): Promise<RegionBoundaries> =>
  import('./boundaries.json?raw').then(
    (module) => JSON.parse(module.default) as RegionBoundaries,
  )
