/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/cells/{cell_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Score, 7-day outlook and factor breakdown for every species in one cell */
    get: operations['get_cell_cells__cell_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/hotspots': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Ranked clusters of high-scoring cells, with nearby recent sightings */
    get: operations['get_hotspots_hotspots_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/scores': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Whole-region grid of conditions scores for one species (or combined) */
    get: operations['get_scores_scores_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sightings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Public sighting counts per cell (never coordinates) */
    get: operations['get_sightings_sightings_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/spot': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Score, 7-day outlook and factor breakdown for every species at a point */
    get: operations['get_spot_spot_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * CellDetailResponse
     * @description Shared shape for `GET /spot` and `GET /cells/{id}`: today plus a
     *     7-day outlook, per species, with the full factor breakdown.
     */
    CellDetailResponse: {
      /** Cell Id */
      cell_id: string
      /** Lat */
      lat: number
      /** Lon */
      lon: number
      place: components['schemas']['Place']
      /** Species */
      species: components['schemas']['SpeciesForecast'][]
    }
    /** DayScore */
    DayScore: {
      /**
       * Date
       * Format: date
       */
      date: string
      /** Factors */
      factors: components['schemas']['FactorBreakdown'][]
      /**
       * Score
       * @description 0-1 conditions index, never a probability
       */
      score: number
    }
    /**
     * FactorBreakdown
     * @description One rule's contribution to a score, in evaluation order (gates, then
     *     drivers, then stoppers) -- the "why this score" breakdown never re-sorts
     *     by magnitude, so the same species always reads in the same order.
     *
     *     `contribution` is this factor's own multiplicative share of the day's
     *     score: the product of every factor's `contribution` equals `score`.
     */
    FactorBreakdown: {
      /** Contribution */
      contribution: number
      /** I18N Key */
      i18n_key: string
      /** Key */
      key: string
      /** Value */
      value: number
    }
    /** GridCellScore */
    GridCellScore: {
      /** Cell Id */
      cell_id: string
      /** Lat */
      lat: number
      /** Lon */
      lon: number
      /** Score */
      score: number
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** Hotspot */
    Hotspot: {
      /** Cell Ids */
      cell_ids: string[]
      /** Id */
      id: string
      /** Lat */
      lat: number
      /** Lon */
      lon: number
      place: components['schemas']['Place']
      /** Recent Sightings */
      recent_sightings: number
      /** Score */
      score: number
    }
    /** HotspotsResponse */
    HotspotsResponse: {
      /**
       * Date
       * Format: date
       */
      date: string
      /** Hotspots */
      hotspots: components['schemas']['Hotspot'][]
      /**
       * Species
       * @enum {string}
       */
      species: 'porcini' | 'ovoli' | 'gallinacci' | 'combined'
    }
    /** Place */
    Place: {
      /** Comune */
      comune: string
      /** Nearest Place */
      nearest_place: string
    }
    /** ScoresResponse */
    ScoresResponse: {
      /** Cells */
      cells: components['schemas']['GridCellScore'][]
      /**
       * Date
       * Format: date
       */
      date: string
      /**
       * Species
       * @enum {string}
       */
      species: 'porcini' | 'ovoli' | 'gallinacci' | 'combined'
    }
    /**
     * SightingCount
     * @description Never coordinates (PRD -> Principles -> Sightings privacy): a count per
     *     cell, source and license.
     */
    SightingCount: {
      /** Cell Id */
      cell_id: string
      /** Count */
      count: number
      /** License */
      license: string
      /**
       * Source
       * @enum {string}
       */
      source: 'gbif' | 'inaturalist'
    }
    /** SightingsResponse */
    SightingsResponse: {
      /** Counts */
      counts: components['schemas']['SightingCount'][]
      /**
       * Since
       * Format: date
       */
      since: string
      /**
       * Species
       * @enum {string}
       */
      species: 'porcini' | 'ovoli' | 'gallinacci'
    }
    /** SpeciesForecast */
    SpeciesForecast: {
      /** Days */
      days: components['schemas']['DayScore'][]
      /**
       * Species
       * @enum {string}
       */
      species: 'porcini' | 'ovoli' | 'gallinacci'
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_cell_cells__cell_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        cell_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CellDetailResponse']
        }
      }
      /** @description unknown cell id */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  get_hotspots_hotspots_get: {
    parameters: {
      query: {
        species: 'porcini' | 'ovoli' | 'gallinacci' | 'combined'
        /** @description defaults to today, Europe/Rome */
        date?: string | null
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HotspotsResponse']
        }
      }
      /** @description date outside the served window */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_scores_scores_get: {
    parameters: {
      query: {
        species: 'porcini' | 'ovoli' | 'gallinacci' | 'combined'
        /** @description defaults to today, Europe/Rome */
        date?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ScoresResponse']
        }
      }
      /** @description date outside the served window */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_sightings_sightings_get: {
    parameters: {
      query: {
        species: 'porcini' | 'ovoli' | 'gallinacci'
        /** @description defaults to one year ago */
        since?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SightingsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_spot_spot_get: {
    parameters: {
      query: {
        lat: number
        lon: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CellDetailResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
