/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/cells/{cell_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Score, 7-day outlook and factor breakdown for every species in one cell */
    get: operations['get_cell_cells__cell_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/comuni': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Comuni with woodland, for the season and outlook views */
    get: operations['get_comuni_comuni_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/factors': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Analysis mode: every factor behind one species' conditions score, per woodland cell */
    get: operations['get_factors_factors_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/history/season/{year}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** One season on the map: good days per woodland cell, comuni ranked by them */
    get: operations['get_season_map_history_season__year__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/history/seasons': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Every stored season for Tuscany or a comune: good days, weather vs normal, sightings */
    get: operations['get_seasons_history_seasons_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/hotspots': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Ranked clusters of high-scoring cells, with nearby recent sightings */
    get: operations['get_hotspots_hotspots_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/outlook': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The season so far and an outlook (not a forecast) for the weeks and months ahead */
    get: operations['get_outlook_outlook_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/scores': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Whole-region grid of conditions scores for one species (or combined) */
    get: operations['get_scores_scores_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sightings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Public sighting counts per cell (never coordinates) */
    get: operations['get_sightings_sightings_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/species': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Plausible species for Tuscany or a comune: habitat fit and good days per season, per species and taxon */
    get: operations['get_species_species_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/spot': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Score, 7-day outlook and factor breakdown for every species at a point */
    get: operations['get_spot_spot_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Data freshness: the latest scored day, when it was generated, and the rules version */
    get: operations['get_status_status_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** Area */
    Area: {
      /**
       * Code
       * @description ISTAT comune code; null for the whole region
       */
      code: string | null
      /**
       * Kind
       * @enum {string}
       */
      kind: 'region' | 'comune'
      /** Name */
      name: string
    }
    /** Baseline */
    Baseline: {
      /**
       * Score Years
       * @description seasons behind the typical good days
       */
      score_years: number[]
      /**
       * Weather Years
       * @description years behind the weather normals
       */
      weather_years: number[]
    }
    /**
     * CellDetailResponse
     * @description Shared shape for `GET /spot` and `GET /cells/{id}`: today plus a
     *     7-day outlook, per species, with the full factor breakdown.
     */
    CellDetailResponse: {
      /** Cell Id */
      cell_id: string
      /**
       * Habitats
       * @description the cell's forest types, largest share first; the shares sum to 1
       */
      habitats: components['schemas']['HabitatShare'][]
      /** Lat */
      lat: number
      /** Lon */
      lon: number
      place: components['schemas']['Place']
      /** Species */
      species: components['schemas']['SpeciesForecast'][]
    }
    /** CellFactors */
    CellFactors: {
      /** Cell Id */
      cell_id: string
      /** Lat */
      lat: number
      /** Lon */
      lon: number
      /**
       * Values
       * @description each factor's 0-1 value, in `factors` order, rounded to 3 decimals: 1 is favourable, 0 holds the score back. From the rule file that wins the cell that day (the one the breakdown explains); null where that rule file lacks the factor
       */
      values: (number | null)[]
    }
    /** CellSeason */
    CellSeason: {
      /** Cell Id */
      cell_id: string
      /** Good Days */
      good_days: number
      /** Lat */
      lat: number
      /** Lon */
      lon: number
    }
    /** Comune */
    Comune: {
      /**
       * Cells
       * @description woodland cells in the comune
       */
      cells: number
      /** Code */
      code: string
      /** Lat */
      lat: number
      /** Lon */
      lon: number
      /** Name */
      name: string
      /** Province */
      province: string
    }
    /** ComuneSeason */
    ComuneSeason: {
      /** Code */
      code: string
      /** Good Days */
      good_days: number
      /** Good Days Typical */
      good_days_typical: number | null
      /** Name */
      name: string
      rain: components['schemas']['RainStat'] | null
      /** Sightings */
      sightings: number
      temperature: components['schemas']['TemperatureStat'] | null
    }
    /** ComuniResponse */
    ComuniResponse: {
      /** Comuni */
      comuni: components['schemas']['Comune'][]
    }
    /** DayScore */
    DayScore: {
      /**
       * Date
       * Format: date
       */
      date: string
      /** Factors */
      factors: components['schemas']['FactorBreakdown'][]
      /**
       * Score
       * @description 0-1 conditions index, never a probability
       */
      score: number
    }
    /**
     * FactorBreakdown
     * @description One rule's contribution to a score, in evaluation order (gates, then
     *     drivers, then stoppers) -- the "why this score" breakdown never re-sorts
     *     by magnitude, so the same species always reads in the same order.
     *
     *     `contribution` is this factor's own multiplicative share of the day's
     *     score: the product of every factor's `contribution` equals `score`.
     *
     *     `input`, `unit` and `days_ago` are the measurement this factor read; they
     *     are null for a factor that measures nothing (season, habitat) and for days
     *     scored without the measurement columns. `rule` says what the rule wanted.
     */
    FactorBreakdown: {
      /** Contribution */
      contribution: number
      /**
       * Days Ago
       * @description rain events: when the rain it scored ended
       */
      days_ago?: number | null
      /**
       * Growth Days
       * @description rain events on a growth clock: the growth since the rain ended, in days at the species' reference pace (warmth speeds it up, cold or dry air slows it down)
       */
      growth_days?: number | null
      /** I18N Key */
      i18n_key: string
      /**
       * Input
       * @description what the factor measured: mm of rain, a temperature, a count of days, metres
       */
      input?: number | null
      /** Key */
      key: string
      /** Role */
      role?: ('gate' | 'driver' | 'stopper') | null
      rule?: components['schemas']['FactorRule'] | null
      /**
       * Unit
       * @description the unit of `input`
       */
      unit?: string | null
      /** Value */
      value: number
      /**
       * Weight
       * @description drivers only
       */
      weight?: number | null
    }
    /**
     * FactorChip
     * @description One indicator analysis mode can put on the map: an enabled factor of the species' rules,
     *     named like its row in the "why this score" breakdown.
     */
    FactorChip: {
      /** I18N Key */
      i18n_key: string
      /**
       * Id
       * @description the factor id, as `key` in the breakdown
       */
      id: string
      /**
       * Role
       * @enum {string}
       */
      role: 'gate' | 'driver' | 'stopper'
    }
    /**
     * FactorRule
     * @description What a rule asked of the measurement (`config/species/*.yaml`), so the copy can say what it
     *     wanted. Which fields are set follows `kind`: a season window or habitat has none of them.
     */
    FactorRule: {
      /**
       * Affinity
       * @description habitat: how well each forest type (`config/habitats.yaml`) suits the taxon, 0-1, for every type; the value is their mean weighted by the cell's `habitats`
       */
      affinity?: {
        [key: string]: number
      } | null
      /**
       * Aggregate
       * @description how a window aggregate combines the days; `percent_of_normal` is their sum as a percentage of the cell's normal for the same days
       */
      aggregate?: ('sum' | 'mean' | 'min' | 'max' | 'percent_of_normal') | null
      /**
       * Kind
       * @enum {string}
       */
      kind:
        | 'season_window'
        | 'habitat'
        | 'static_band'
        | 'rain_event'
        | 'window_aggregate'
        | 'count_days'
        | 'days_since'
      /**
       * Lag Days
       * @description rain events: the same shape over the lag the rain may have, in `lag_unit`
       */
      lag_days?: (number | null)[] | null
      /**
       * Lag Unit
       * @description rain events: `days` when `lag_days` counts calendar days (`days_ago`), `growth_days` when it counts the species' growth since the rain (`growth_days`)
       */
      lag_unit?: ('days' | 'growth_days') | null
      /**
       * Offset Days
       * @description the window ends this many days before the scored day
       */
      offset_days?: number | null
      /**
       * Op
       * @description what counts as a matching day, against `threshold`
       */
      op?: ('lt' | 'lte' | 'gt' | 'gte') | null
      /** Threshold */
      threshold?: number | null
      /**
       * Trapezoid
       * @description [zero_below, full_from, full_to, zero_above] over the measurement (`input`, in `unit`); a null pair leaves that side open
       */
      trapezoid?: (number | null)[] | null
      /**
       * Variable
       * @description the weather variable or cell attribute the factor reads
       */
      variable?: string | null
      /**
       * Variable Unit
       * @description the unit of `variable` (and of `threshold`); '' when unitless
       */
      variable_unit?: string | null
      /** @description gates and stoppers that apply only in part of the region */
      where?: components['schemas']['FactorWhere'] | null
      /**
       * Window Days
       * @description days of rain a rain event adds up, the days an aggregate or count spans, or how far back days_since looks
       */
      window_days?: number | null
    }
    /**
     * FactorWhere
     * @description Where a gate or stopper applies: its effect fades out as the cell's `variable` leaves the
     *     trapezoid (full effect on the plateau, none outside).
     */
    FactorWhere: {
      /**
       * Trapezoid
       * @description [zero_below, full_from, full_to, zero_above] over `variable`
       */
      trapezoid: (number | null)[]
      /**
       * Variable
       * @description the cell attribute the condition reads
       */
      variable: string
      /**
       * Variable Unit
       * @description the unit of `variable`; '' when unitless
       */
      variable_unit: string
    }
    /**
     * FactorsResponse
     * @description Analysis mode: every factor behind a species' conditions score, per woodland cell, for one
     *     day. Only the days the daily job keeps the breakdown for (today -6 to +7) are stored.
     */
    FactorsResponse: {
      /** Cells */
      cells: components['schemas']['CellFactors'][]
      /**
       * Date
       * Format: date
       */
      date: string
      /**
       * Factors
       * @description the union of the enabled factors over the species' rule files, in breakdown order (gates, drivers, stoppers)
       */
      factors: components['schemas']['FactorChip'][]
      /**
       * Species
       * @enum {string}
       */
      species: 'porcini' | 'ovoli' | 'gallinacci'
    }
    /** GridCellScore */
    GridCellScore: {
      /** Cell Id */
      cell_id: string
      /** Lat */
      lat: number
      /** Lon */
      lon: number
      /** Score */
      score: number
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HabitatShare */
    HabitatShare: {
      /**
       * Fraction
       * @description its share of the cell's wooded area
       */
      fraction: number
      /**
       * Habitat
       * @description the forest type, a habitat of `config/habitats.yaml`
       */
      habitat: string
    }
    /** Hotspot */
    Hotspot: {
      /** Cell Ids */
      cell_ids: string[]
      /** Id */
      id: string
      /** Lat */
      lat: number
      /** Lon */
      lon: number
      place: components['schemas']['Place']
      /** Recent Sightings */
      recent_sightings: number
      /** Score */
      score: number
    }
    /** HotspotsResponse */
    HotspotsResponse: {
      /**
       * Date
       * Format: date
       */
      date: string
      /** Hotspots */
      hotspots: components['schemas']['Hotspot'][]
      /**
       * Species
       * @enum {string}
       */
      species: 'porcini' | 'ovoli' | 'gallinacci' | 'combined'
    }
    /** MonthStat */
    MonthStat: {
      /**
       * Good Days
       * @description a typical woodland cell's good days
       */
      good_days: number
      /** Month */
      month: number
      rain: components['schemas']['RainStat'] | null
      /** Sightings */
      sightings: number
      temperature: components['schemas']['TemperatureStat'] | null
    }
    /**
     * OutlookPeriod
     * @description A week (EC46) or month (SEAS5) after the 7-day forecast. An outlook, not a forecast.
     */
    OutlookPeriod: {
      /**
       * End
       * Format: date
       */
      end: string
      /**
       * Kind
       * @enum {string}
       */
      kind: 'week' | 'month'
      /**
       * Lead Rain Pct
       * @description rain over the lead window, as a percentage of normal
       */
      lead_rain_pct: number | null
      /**
       * Outlook
       * @enum {string}
       */
      outlook: 'better' | 'usual' | 'worse' | 'unknown'
      /**
       * Past Good Years
       * @description past seasons in which these days were good
       */
      past_good_years: number
      /**
       * Past Years
       * @description past seasons with scores for these days
       */
      past_years: number
      /** @description long-range forecast total and its own normal */
      rain: components['schemas']['RainStat'] | null
      /**
       * Start
       * Format: date
       */
      start: string
      /** Temperature Anomaly C */
      temperature_anomaly_c: number | null
    }
    /** OutlookResponse */
    OutlookResponse: {
      area: components['schemas']['Area']
      baseline: components['schemas']['Baseline']
      /** Good Share */
      good_share: number
      /**
       * Issued
       * @description when the long-range forecast was fetched
       */
      issued: string | null
      /** Periods */
      periods: components['schemas']['OutlookPeriod'][]
      rain_lead: components['schemas']['RainLead']
      rain_tilt: components['schemas']['RainTiltBands']
      season_to_date: components['schemas']['SeasonToDate'] | null
      /**
       * Species
       * @enum {string}
       */
      species: 'porcini' | 'ovoli' | 'gallinacci'
      window: components['schemas']['SeasonWindow']
    }
    /** Place */
    Place: {
      /** Comune */
      comune: string
      /** Nearest Place */
      nearest_place: string
    }
    /**
     * PlausibleSpeciesResponse
     * @description Which species an area's woodland plausibly holds, from habitat and altitude alone (weather
     *     and season aside), and how each species and taxon fared in every stored season.
     */
    PlausibleSpeciesResponse: {
      area: components['schemas']['Area']
      /** Good Score */
      good_score: number
      /**
       * Plausible Fit
       * @description the habitat x altitude fit a cell needs for a taxon to count
       */
      plausible_fit: number
      /** Species */
      species: components['schemas']['SpeciesProfile'][]
    }
    /** RainLead */
    RainLead: {
      /** Max Days */
      max_days: number
      /** Min Days */
      min_days: number
    }
    /** RainStat */
    RainStat: {
      /** Normal Mm */
      normal_mm: number
      /** Total Mm */
      total_mm: number
    }
    /**
     * RainTiltBands
     * @description Lead-window rain at or above ``wetter_pct`` of normal tilts a period better; at or below
     *     ``drier_pct``, worse (``config/history.yaml``).
     */
    RainTiltBands: {
      /** Drier Pct */
      drier_pct: number
      /** Wetter Pct */
      wetter_pct: number
    }
    /** ScoresResponse */
    ScoresResponse: {
      /** Cells */
      cells: components['schemas']['GridCellScore'][]
      /**
       * Date
       * Format: date
       */
      date: string
      /**
       * Species
       * @enum {string}
       */
      species: 'porcini' | 'ovoli' | 'gallinacci' | 'combined'
    }
    /**
     * SeasonMapResponse
     * @description One season on the map: good days per woodland cell, and the comuni ranked by them.
     */
    SeasonMapResponse: {
      /** Cells */
      cells: components['schemas']['CellSeason'][]
      /** Complete */
      complete: boolean
      /** Comuni */
      comuni: components['schemas']['ComuneSeason'][]
      /** Good Score */
      good_score: number
      /**
       * Species
       * @enum {string}
       */
      species: 'porcini' | 'ovoli' | 'gallinacci' | 'combined'
      /**
       * Through
       * Format: date
       */
      through: string
      /** Year */
      year: number
    }
    /** SeasonSummary */
    SeasonSummary: {
      /**
       * Complete
       * @description every day of the year is scored
       */
      complete: boolean
      /**
       * Good Days
       * @description a typical woodland cell's good days
       */
      good_days: number
      /**
       * Good Days Typical
       * @description median over the baseline seasons, to the same day of the year
       */
      good_days_typical: number | null
      /** Months */
      months: components['schemas']['MonthStat'][]
      /** Peak Date */
      peak_date: string | null
      /**
       * Peak Share
       * @description share of woodland cells good that day
       */
      peak_share: number
      /** @description over the observed days of the window */
      rain: components['schemas']['RainStat'] | null
      /** Sightings */
      sightings: number
      temperature: components['schemas']['TemperatureStat'] | null
      /**
       * Through
       * Format: date
       * @description the last day scored
       */
      through: string
      /**
       * Weather Through
       * @description the last observed day behind the weather
       */
      weather_through: string | null
      window: components['schemas']['SeasonWindow']
      /** Year */
      year: number
    }
    /** SeasonToDate */
    SeasonToDate: {
      /** Good Days */
      good_days: number
      /** Good Days Typical */
      good_days_typical: number | null
      rain: components['schemas']['RainStat'] | null
      /** Sightings */
      sightings: number
      temperature: components['schemas']['TemperatureStat'] | null
      /**
       * Through
       * Format: date
       */
      through: string
      /** Weather Through */
      weather_through: string | null
    }
    /**
     * SeasonWindow
     * @description The span of the species' season windows in its rule files, for one year.
     */
    SeasonWindow: {
      /**
       * End
       * Format: date
       */
      end: string
      /**
       * Start
       * Format: date
       */
      start: string
    }
    /** SeasonsResponse */
    SeasonsResponse: {
      area: components['schemas']['Area']
      baseline: components['schemas']['Baseline']
      /** Good Score */
      good_score: number
      /** Seasons */
      seasons: components['schemas']['SeasonSummary'][]
      /**
       * Species
       * @enum {string}
       */
      species: 'porcini' | 'ovoli' | 'gallinacci' | 'combined'
    }
    /**
     * SightingCount
     * @description Never coordinates (PRD -> Principles -> Sightings privacy): a count per
     *     cell, source and license.
     */
    SightingCount: {
      /** Cell Id */
      cell_id: string
      /** Count */
      count: number
      /** License */
      license: string
      /**
       * Source
       * @enum {string}
       */
      source: 'gbif' | 'inaturalist'
    }
    /** SightingsResponse */
    SightingsResponse: {
      /** Counts */
      counts: components['schemas']['SightingCount'][]
      /**
       * Since
       * Format: date
       */
      since: string
      /**
       * Species
       * @enum {string}
       */
      species: 'porcini' | 'ovoli' | 'gallinacci'
    }
    /** SpeciesForecast */
    SpeciesForecast: {
      /** Days */
      days: components['schemas']['DayScore'][]
      /**
       * Species
       * @enum {string}
       */
      species: 'porcini' | 'ovoli' | 'gallinacci'
    }
    /** SpeciesProfile */
    SpeciesProfile: {
      /**
       * Fit Share
       * @description share of the area's woodland plausible for any of its taxa
       */
      fit_share: number
      /**
       * Seasons
       * @description good days per season, oldest first
       */
      seasons: components['schemas']['SpeciesSeason'][]
      /**
       * Species
       * @enum {string}
       */
      species: 'porcini' | 'ovoli' | 'gallinacci'
      /** Taxa */
      taxa: components['schemas']['TaxonProfile'][]
    }
    /** SpeciesSeason */
    SpeciesSeason: {
      /**
       * Good Days
       * @description a typical woodland cell's good days
       */
      good_days: number
      /** Year */
      year: number
    }
    /**
     * StatusResponse
     * @description Data freshness, for the frontend's "last updated" and stale-data warning (M7).
     */
    StatusResponse: {
      /**
       * Rules Version
       * @description the species rule config's version stamp; null before the first pipeline run
       */
      rules_version: string | null
      /**
       * Scored Through
       * Format: date
       * @description the latest day the pipeline has scored
       */
      scored_through: string
      /**
       * Updated At
       * @description when the scores were last (re)generated; null before the first pipeline run
       */
      updated_at: string | null
    }
    /** TaxonProfile */
    TaxonProfile: {
      /**
       * Fit Share
       * @description share of the area's woodland whose habitat and altitude plausibly suit it
       */
      fit_share: number
      /** I18N Key */
      i18n_key: string
      /**
       * Key
       * @description the taxon's rule set, e.g. porcini_edulis
       */
      key: string
      /**
       * Seasons
       * @description its own good days per season, oldest first
       */
      seasons: components['schemas']['SpeciesSeason'][]
      /**
       * Taxon
       * @description scientific name, as the rule set gives it
       */
      taxon: string
    }
    /** TemperatureStat */
    TemperatureStat: {
      /** Mean C */
      mean_c: number
      /** Normal C */
      normal_c: number
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_cell_cells__cell_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        cell_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CellDetailResponse']
        }
      }
      /** @description unknown cell id */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_comuni_comuni_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ComuniResponse']
        }
      }
      /** @description history not built yet */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_factors_factors_get: {
    parameters: {
      query: {
        species: 'porcini' | 'ovoli' | 'gallinacci'
        /** @description defaults to today, Europe/Rome */
        date?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FactorsResponse']
        }
      }
      /** @description no factors stored for that day */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  get_season_map_history_season__year__get: {
    parameters: {
      query: {
        species: 'porcini' | 'ovoli' | 'gallinacci' | 'combined'
      }
      header?: never
      path: {
        year: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SeasonMapResponse']
        }
      }
      /** @description season not stored */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description history not built yet */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_seasons_history_seasons_get: {
    parameters: {
      query?: {
        /** @description ISTAT comune code (see /comuni); omit for all of Tuscany */
        comune?: string | null
        species?: 'porcini' | 'ovoli' | 'gallinacci' | 'combined'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SeasonsResponse']
        }
      }
      /** @description unknown comune */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description history not built yet */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_hotspots_hotspots_get: {
    parameters: {
      query: {
        species: 'porcini' | 'ovoli' | 'gallinacci' | 'combined'
        /** @description defaults to today, Europe/Rome */
        date?: string | null
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HotspotsResponse']
        }
      }
      /** @description date outside the served window */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_outlook_outlook_get: {
    parameters: {
      query: {
        species: 'porcini' | 'ovoli' | 'gallinacci'
        /** @description ISTAT comune code (see /comuni); omit for all of Tuscany */
        comune?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OutlookResponse']
        }
      }
      /** @description unknown comune */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description history not built yet */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_scores_scores_get: {
    parameters: {
      query: {
        species: 'porcini' | 'ovoli' | 'gallinacci' | 'combined'
        /** @description defaults to today, Europe/Rome */
        date?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ScoresResponse']
        }
      }
      /** @description date outside the served window */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_sightings_sightings_get: {
    parameters: {
      query: {
        species: 'porcini' | 'ovoli' | 'gallinacci'
        /** @description defaults to one year ago */
        since?: string | null
        /** @description last day included; defaults to no limit */
        until?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SightingsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_species_species_get: {
    parameters: {
      query?: {
        /** @description ISTAT comune code (see /comuni); omit for all of Tuscany */
        comune?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlausibleSpeciesResponse']
        }
      }
      /** @description unknown comune */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description history not built yet */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_spot_spot_get: {
    parameters: {
      query: {
        lat: number
        lon: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CellDetailResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_status_status_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
      /** @description the pipeline has never scored anything yet */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
